### ISSUE TITLE
generate derived files without remaking the pdf?

### ISSUE THREAD

**Issue by kberry** [francesco-contini/biblatex-accursius#1]
Hi Francois - I just imported your newbiblatex-accursius package (thanks for contributing) to TeX Live. It seems that processing the
dtx always (I think) tries to regenerate the documentation.  That is not
desirable: I want to use your .pdf.  Thus it would be excellent if
generating the .cls/whatever files from the dtx was separated from
making the documentation.

Most packages just generate files when "latex" (or "etex" or
..). is used, vs. remaking the documentation with xelatex or lualatex, etc. Unfortunately I don't have an exact recipe for your case, but I hope it will be possible. Thanks.

**Comment by francesco-contini** [comment]
Hi there and thanks for your interest in this bundle.
I’m sorry, if this response seems a bit basic, but I’m still learning, as affirmed in the readmi file.
Am I wrong, or are you asking me to upload an .ins extension file, to be ran with `latex \jobname.ins`? If so, I’ll update this repository.

**Comment by kberry** [comment]
Hi Francesco - I'm not sure if a separate .ins file would solve the
problem, but I think so. The goal is to be able to create the derived
files without also regenerating the pdf. Thanks.

**Comment by francesco-contini** [comment]
Okay. So, I created and uploaded the .ins file. I specified that it should generate `.bbx`, `.cbx` and the three `.blx` files.

**Comment by francesco-contini** [comment]
If I run `latex biblatex-accursius.ins`, I finally get only the five files named and the `.log` one. I hope this is just what you are looking for.
